[package]
name = "dreg"
version = "0.1.0"
edition = "2021"



[features]
default = ["all"]
all = ["anim", "mouse"]
anim = ["dep:rand"]
mouse = []


[dependencies]
anyhow = "1.0.86"
bitflags = "2.6.0"
compact_str = "0.7.1"
crossterm = "0.27.0"
rand = { version = "0.8.5", features = ["small_rng"], optional = true }
unicode-segmentation = "1.10.1"
unicode-width = "0.1.13"
