[package]
name = "dreg"
version = "1.0.0"
authors = ["Matthew Martin"]
edition = "2021"
description = "A simple terminal user interface library"
readme = "README.md"
homepage = "https://rtthw.github.io/dreg"
repository = "https://github.com/rtthw/dreg"
license-file = "LICENSE"
# keywords = [""]
# categories = [""]

[features]
default = ["crossterm"]
crossterm = ["dep:dreg-crossterm"]

[dependencies]
dreg-core = { workspace = true }
dreg-crossterm = { path = "crates/dreg-crossterm", optional = true }

[workspace]
members = ["crates/dreg-core", "crates/dreg-crossterm"]

[workspace.dependencies]
dreg-core = { path = "crates/dreg-core" }
