[package]
name = "dreg"
version = "0.3.0"
authors = ["Matthew Norman"]
edition = "2021"
description = "A simple text-based user interface library"
readme = "README.md"
homepage = "https://github.com/rtthw/dreg"
repository = "https://github.com/rtthw/dreg"
license = "MIT"

[features]
default = ["native"]
native = ["dep:winit", "dep:softbuffer"]
web = []

[dependencies]
bitflags = "2"
compact_str = "0.8"
softbuffer = { version = "0.4", optional = true }
winit = { version = "0.29", optional = true }     # TODO: Update to 0.30
