[package]
name = "dreg"
version = "0.3.0"
authors = ["Matthew Norman"]
edition = "2021"
description = "A simple text-based user interface library"
readme = "README.md"
homepage = "https://github.com/rtthw/dreg"
repository = "https://github.com/rtthw/dreg"
license = "MIT"

[features]
default = ["native"]
native = [
    # "dep:ab_glyph",
    "dep:epaint_default_fonts",
    "dep:glow",
    "dep:glow_glyph",
    "dep:glutin",
    # "dep:softbuffer",
]
web = []

[dependencies]
# ab_glyph = { version = "0.2", optional = true }
bitflags = "2"
compact_str = "0.8"
epaint_default_fonts = { version = "0.30", optional = true }
glow = { version = "0.13", optional = true }
glow_glyph = { version = "0.7", optional = true }
# softbuffer = { version = "0.4", optional = true }
glutin = { version = "0.29", optional = true } # TODO: Update to 0.30
