[package]
name = "dreg"
version.workspace = true
authors = ["Matthew Martin"]
edition.workspace = true
description = "A simple text-based user interface library"
readme = "README.md"
homepage.workspace = true
repository = "https://github.com/rtthw/dreg"
license.workspace = true
# keywords = [""]
# categories = [""]

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[features]
default = ["term"]
term = ["dep:dreg-term"]
wasm = ["dep:dreg-wasm"]

[dependencies]
dreg-core = { workspace = true }
dreg-term = { version = "0.2.2", path = "crates/dreg-term", optional = true }
dreg-wasm = { version = "0.2.2", path = "crates/dreg-wasm", optional = true }

[workspace]
resolver = "2"
members = ["crates/dreg-core", "crates/dreg-term", "crates/dreg-wasm"]

[workspace.package]
version = "0.2.2"
edition = "2021"
homepage = "https://rtthw.github.io/dreg"
license = "MIT"

[workspace.dependencies]
dreg-core = { version = "0.2.2", path = "crates/dreg-core" }
