[package]
name = "dreg-term"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository = "https://github.com/rtthw/dreg/dreg-term"
license.workspace = true

[dependencies]
