[package]
name = "dreg-native"
version.workspace = true
authors.workspace = true
edition.workspace = true
readme.workspace = true
homepage.workspace = true
repository = "https://github.com/rtthw/dreg/dreg-native"
license.workspace = true

[dependencies]
