[package]
name = "dreg"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository = "https://github.com/rtthw/dreg/dreg"
license.workspace = true

[features]
default = []
wasm = ["dep:dreg-wasm"]

[dependencies]
dreg-core = { workspace = true }
dreg-wasm = { version = "0.3.0", path = "../dreg-wasm", optional = true }
